server:
  servlet:
    context-path: /payment
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/upgrad
    username:
    password:

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl